stages:
  prepare:
    cmd: python3 src/data/prepare_data.py ./data
    deps:
    - src/data/prepare_data.py
  train:
    cmd: python3 src/models/train_model.py
    deps:
    - src/models/train_model.py

    # metrics:
    # - report/metrics.json:
    #     cache: false
  predict:
    cmd: python3 src/models/predict_model.py
    deps:
    - src/models/predict_model.py
   


#
